---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/test":
    get:
      summary: Test endpoint
      responses:
        '200':
          description: success
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
